apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
  namespace: app-dev
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - app.dev.local
    port:
      name: http
      number: 80
      protocol: HTTP
