apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-deployment
  namespace: app-dev
  labels:
    app: app02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app02
  template:
    metadata:
      labels:
        app: app02
    spec:
      containers:
        - name: app02
          image: mouradev01/app02:v8
          ports:
            - containerPort: 3000