blank_issues_enabled: false
contact_links:
  - name: Ajuda - fórum de discussão 
    url: https://github.com/leoviana00/lab-k8s-prep-cks/discussions
    about: Por favor, pergunte e responda perguntas aqui.
  - name: Relatar vulnerabilidades de segurança,
    url: https://github.com/leoviana00/lab-k8s-prep-cks/blob/main/SECURITY.md
    about: Para relatar vulnerabilidades de segurança, lei aqui.
