apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deployment
  namespace: app-dev
  labels:
    app: app01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: app01
          image: mouradev01/app01:v8
          ports:
            - containerPort: 3000